services:
  server:
    build:
      context: .
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DOMAIN_NAME: ${DOMAIN}
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project-feasibility-study-router.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.project-feasibility-study-router.entrypoints=websecure"
      - "traefik.http.routers.project-feasibility-study-router.tls.certresolver=myresolver"
      - "traefik.http.routers.project-feasibility-study-router.service=project-feasibility-study-service"
      - "traefik.http.services.project-feasibility-study-service.loadbalancer.server.port=${PORT}"

networks:
  traefik-public:
    external: true